/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CorporateGiftingRouteImport } from './routes/corporate-gifting'
import { Route as CustomSculptureRouteImport } from './routes/custom-sculpture'
import { Route as CustomizeIdolRouteImport } from './routes/customize-idol'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as TrackOrderRouteImport } from './routes/track-order'
import { Route as WishlistRouteImport } from './routes/wishlist'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAlertsRouteImport } from './routes/admin.alerts'
import { Route as AdminCollectionsRouteImport } from './routes/admin.collections'
import { Route as AdminDataRouteImport } from './routes/admin.data'
import { Route as AdminEmailRouteImport } from './routes/admin.email'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AuthBridgeRouteImport } from './routes/auth_.bridge'
import { Route as CollectionsSlugRouteImport } from './routes/collections.$slug'
import { Route as OrderIdRouteImport } from './routes/order.$id'
import { Route as PoliciesSlugRouteImport } from './routes/policies.$slug'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as ApiPublicCartRemindersRouteImport } from './routes/api/public/cart-reminders'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CorporateGiftingRoute = CorporateGiftingRouteImport.update({
  id: '/corporate-gifting',
  path: '/corporate-gifting',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomSculptureRoute = CustomSculptureRouteImport.update({
  id: '/custom-sculpture',
  path: '/custom-sculpture',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomizeIdolRoute = CustomizeIdolRouteImport.update({
  id: '/customize-idol',
  path: '/customize-idol',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackOrderRoute = TrackOrderRouteImport.update({
  id: '/track-order',
  path: '/track-order',
  getParentRoute: () => rootRouteImport,
} as any)
const WishlistRoute = WishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlertsRoute = AdminAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCollectionsRoute = AdminCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDataRoute = AdminDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailRoute = AdminEmailRouteImport.update({
  id: '/email',
  path: '/email',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AuthBridgeRoute = AuthBridgeRouteImport.update({
  id: '/auth_/bridge',
  path: '/auth/bridge',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesSlugRoute = PoliciesSlugRouteImport.update({
  id: '/policies/$slug',
  path: '/policies/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCartRemindersRoute = ApiPublicCartRemindersRouteImport.update({
  id: '/api/public/cart-reminders',
  path: '/api/public/cart-reminders',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/corporate-gifting': typeof CorporateGiftingRoute
  '/custom-sculpture': typeof CustomSculptureRoute
  '/customize-idol': typeof CustomizeIdolRoute
  '/faq': typeof FaqRoute
  '/track-order': typeof TrackOrderRoute
  '/wishlist': typeof WishlistRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/collections': typeof AdminCollectionsRoute
  '/admin/data': typeof AdminDataRoute
  '/admin/email': typeof AdminEmailRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/auth/bridge': typeof AuthBridgeRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/order/$id': typeof OrderIdRoute
  '/policies/$slug': typeof PoliciesSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/cart-reminders': typeof ApiPublicCartRemindersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/corporate-gifting': typeof CorporateGiftingRoute
  '/custom-sculpture': typeof CustomSculptureRoute
  '/customize-idol': typeof CustomizeIdolRoute
  '/faq': typeof FaqRoute
  '/track-order': typeof TrackOrderRoute
  '/wishlist': typeof WishlistRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/collections': typeof AdminCollectionsRoute
  '/admin/data': typeof AdminDataRoute
  '/admin/email': typeof AdminEmailRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/auth/bridge': typeof AuthBridgeRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/order/$id': typeof OrderIdRoute
  '/policies/$slug': typeof PoliciesSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/cart-reminders': typeof ApiPublicCartRemindersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/corporate-gifting': typeof CorporateGiftingRoute
  '/custom-sculpture': typeof CustomSculptureRoute
  '/customize-idol': typeof CustomizeIdolRoute
  '/faq': typeof FaqRoute
  '/track-order': typeof TrackOrderRoute
  '/wishlist': typeof WishlistRoute
  '/admin/alerts': typeof AdminAlertsRoute
  '/admin/collections': typeof AdminCollectionsRoute
  '/admin/data': typeof AdminDataRoute
  '/admin/email': typeof AdminEmailRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/auth_/bridge': typeof AuthBridgeRoute
  '/collections/$slug': typeof CollectionsSlugRoute
  '/order/$id': typeof OrderIdRoute
  '/policies/$slug': typeof PoliciesSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/cart-reminders': typeof ApiPublicCartRemindersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/corporate-gifting'
    | '/custom-sculpture'
    | '/customize-idol'
    | '/faq'
    | '/track-order'
    | '/wishlist'
    | '/admin/alerts'
    | '/admin/collections'
    | '/admin/data'
    | '/admin/email'
    | '/admin/orders'
    | '/admin/settings'
    | '/auth/bridge'
    | '/collections/$slug'
    | '/order/$id'
    | '/policies/$slug'
    | '/products/$slug'
    | '/admin/'
    | '/api/public/cart-reminders'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/corporate-gifting'
    | '/custom-sculpture'
    | '/customize-idol'
    | '/faq'
    | '/track-order'
    | '/wishlist'
    | '/admin/alerts'
    | '/admin/collections'
    | '/admin/data'
    | '/admin/email'
    | '/admin/orders'
    | '/admin/settings'
    | '/auth/bridge'
    | '/collections/$slug'
    | '/order/$id'
    | '/policies/$slug'
    | '/products/$slug'
    | '/admin'
    | '/api/public/cart-reminders'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/account'
    | '/admin'
    | '/auth'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/corporate-gifting'
    | '/custom-sculpture'
    | '/customize-idol'
    | '/faq'
    | '/track-order'
    | '/wishlist'
    | '/admin/alerts'
    | '/admin/collections'
    | '/admin/data'
    | '/admin/email'
    | '/admin/orders'
    | '/admin/settings'
    | '/auth_/bridge'
    | '/collections/$slug'
    | '/order/$id'
    | '/policies/$slug'
    | '/products/$slug'
    | '/admin/'
    | '/api/public/cart-reminders'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  CorporateGiftingRoute: typeof CorporateGiftingRoute
  CustomSculptureRoute: typeof CustomSculptureRoute
  CustomizeIdolRoute: typeof CustomizeIdolRoute
  FaqRoute: typeof FaqRoute
  TrackOrderRoute: typeof TrackOrderRoute
  WishlistRoute: typeof WishlistRoute
  AuthBridgeRoute: typeof AuthBridgeRoute
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  OrderIdRoute: typeof OrderIdRoute
  PoliciesSlugRoute: typeof PoliciesSlugRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  ApiPublicCartRemindersRoute: typeof ApiPublicCartRemindersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corporate-gifting': {
      id: '/corporate-gifting'
      path: '/corporate-gifting'
      fullPath: '/corporate-gifting'
      preLoaderRoute: typeof CorporateGiftingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-sculpture': {
      id: '/custom-sculpture'
      path: '/custom-sculpture'
      fullPath: '/custom-sculpture'
      preLoaderRoute: typeof CustomSculptureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customize-idol': {
      id: '/customize-idol'
      path: '/customize-idol'
      fullPath: '/customize-idol'
      preLoaderRoute: typeof CustomizeIdolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-order': {
      id: '/track-order'
      path: '/track-order'
      fullPath: '/track-order'
      preLoaderRoute: typeof TrackOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wishlist': {
      id: '/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof WishlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alerts': {
      id: '/admin/alerts'
      path: '/alerts'
      fullPath: '/admin/alerts'
      preLoaderRoute: typeof AdminAlertsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/collections': {
      id: '/admin/collections'
      path: '/collections'
      fullPath: '/admin/collections'
      preLoaderRoute: typeof AdminCollectionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/data': {
      id: '/admin/data'
      path: '/data'
      fullPath: '/admin/data'
      preLoaderRoute: typeof AdminDataRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/email': {
      id: '/admin/email'
      path: '/email'
      fullPath: '/admin/email'
      preLoaderRoute: typeof AdminEmailRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/auth_/bridge': {
      id: '/auth_/bridge'
      path: '/auth/bridge'
      fullPath: '/auth/bridge'
      preLoaderRoute: typeof AuthBridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/$slug': {
      id: '/policies/$slug'
      path: '/policies/$slug'
      fullPath: '/policies/$slug'
      preLoaderRoute: typeof PoliciesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cart-reminders': {
      id: '/api/public/cart-reminders'
      path: '/api/public/cart-reminders'
      fullPath: '/api/public/cart-reminders'
      preLoaderRoute: typeof ApiPublicCartRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAlertsRoute: typeof AdminAlertsRoute
  AdminCollectionsRoute: typeof AdminCollectionsRoute
  AdminDataRoute: typeof AdminDataRoute
  AdminEmailRoute: typeof AdminEmailRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAlertsRoute: AdminAlertsRoute,
  AdminCollectionsRoute: AdminCollectionsRoute,
  AdminDataRoute: AdminDataRoute,
  AdminEmailRoute: AdminEmailRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  CorporateGiftingRoute: CorporateGiftingRoute,
  CustomSculptureRoute: CustomSculptureRoute,
  CustomizeIdolRoute: CustomizeIdolRoute,
  FaqRoute: FaqRoute,
  TrackOrderRoute: TrackOrderRoute,
  WishlistRoute: WishlistRoute,
  AuthBridgeRoute: AuthBridgeRoute,
  CollectionsSlugRoute: CollectionsSlugRoute,
  OrderIdRoute: OrderIdRoute,
  PoliciesSlugRoute: PoliciesSlugRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  ApiPublicCartRemindersRoute: ApiPublicCartRemindersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
